import numpy as np  
A = np.array([ [12, 5, 8, 20], [ 7, 15, 3, 11], [25, 9, 18, 6], [10, 14, 2, 16] ])  
Perform the following without using explicit Python for loops:
1. Calculate the mean of each row.
2. Replace every element that is greater than its row mean by 1.
3. Replace every other element by 0.
4. Return the resulting binary matrix.
5. Also determine which row contains the maximum number of elements
above its row mean.

In [28]:
import numpy as np
A = np.array([
    [12, 5, 8, 20],
    [7, 15, 3, 11],
    [25, 9, 18, 6],
    [10, 14, 2, 16]
])

In [29]:
mean = np.mean(A, axis=1)
mean

array([11.25,  9.  , 14.5 , 10.5 ])

In [30]:
B = np.where(A > mean[:, None], 1, 0)
B

array([[1, 0, 0, 1],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [31]:
count = np.sum(B, axis=1)
count

array([2, 2, 2, 2])

In [32]:
row = np.argmax(count) + 1
row

np.int64(1)

X = np.array([ [10, 100, 5], [12, 110, 6], [11, 105, 7], [13, 500, 6], [14, 108, 8], [15,
115, 9] ])
For each column:
1. Calculate the mean and standard deviation.
2. Identify values satisfying:
∣x−μ∣>2σ
3. Replace such values with the corresponding column median.
4. Do this without modifying non-outlier values.

In [33]:
import numpy as np

X = np.array([
    [10, 100, 5],
    [12, 110, 6],
    [11, 105, 7],
    [13, 500, 6],
    [14, 108, 8],
    [15, 115, 9]
])

In [34]:
mean = np.mean(X, axis=0)
mean

array([ 12.5       , 173.        ,   6.83333333])

In [35]:
std = np.std(X, axis=0)
std

array([  1.70782513, 146.31017281,   1.34370962])

In [36]:
outlier = np.abs(X - mean) > 2 * std
outlier

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [37]:
median = np.median(X, axis=0)
median

array([ 12.5, 109. ,   6.5])

In [38]:
X_new = np.where(outlier, median, X)
X_new

array([[ 10., 100.,   5.],
       [ 12., 110.,   6.],
       [ 11., 105.,   7.],
       [ 13., 109.,   6.],
       [ 14., 108.,   8.],
       [ 15., 115.,   9.]])

P = np.array([ [1, 2], [4, 6], [7, 3], [2, 8], [9, 5] ])  
Construct a 5×5 matrix where element (i,j) contains the Euclidean distance
between points i and j.
The solution must:
● use NumPy broadcasting;
● contain no for or while loop;
● have zeros on the diagonal;
● produce a symmetric matrix.
Then identify the pair of points having the maximum distance.

In [39]:
import numpy as np

P = np.array([
    [1, 2],
    [4, 6],
    [7, 3],
    [2, 8],
    [9, 5]
])
dx = P[:, 0, None] - P[:, 0]
dy = P[:, 1, None] - P[:, 1]

D = np.sqrt(dx**2 + dy**2)

print("Distance matrix:")
print(D)

max_dist = np.max(D)

i, j = np.unravel_index(np.argmax(D), D.shape)

print("Maximum distance:", max_dist)
print("Points:", i + 1, "and", j + 1)

Distance matrix:
[[0.         5.         6.08276253 6.08276253 8.54400375]
 [5.         0.         4.24264069 2.82842712 5.09901951]
 [6.08276253 4.24264069 0.         7.07106781 2.82842712]
 [6.08276253 2.82842712 7.07106781 0.         7.61577311]
 [8.54400375 5.09901951 2.82842712 7.61577311 0.        ]]
Maximum distance: 8.54400374531753
Points: 1 and 5

import pandas as pd  
df = pd.DataFrame({ 'Student': ['A','B','C','D','E','F','G','H'],  
'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],  
'Gender': ['F','M','F','M','M','F','F','M'],  
'Marks': [85,72,91,65,78,88,95,70],
'Attendance': [92,81,96,72,85,90,98,75] })  
Find:
1. Average marks for each department.
2. Average marks separately for each (Department, Gender) group.
3. Student with the highest marks in each department.
4. Students whose marks are above their department average.
5. Department having the highest average attendance

In [40]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A','B','C','D','E','F','G','H'],
    'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],
    'Gender': ['F','M','F','M','M','F','F','M'],
    'Marks': [85,72,91,65,78,88,95,70],
    'Attendance': [92,81,96,72,85,90,98,75]
})

In [41]:
df.groupby('Department')['Marks'].mean()

Department
CSE    82.5
ECE    78.5
Name: Marks, dtype: float64

In [42]:
df.groupby(['Department', 'Gender'])['Marks'].mean()

Department  Gender
CSE         F         90.0
            M         75.0
ECE         F         89.5
            M         67.5
Name: Marks, dtype: float64

In [43]:
cse = df[df['Department'] == 'CSE']
cse[cse['Marks'] == cse['Marks'].max()]

  Student Department Gender  Marks  Attendance
6       G        CSE      F     95          98

In [44]:
ece = df[df['Department'] == 'ECE']
ece[ece['Marks'] == ece['Marks'].max()]

  Student Department Gender  Marks  Attendance
2       C        ECE      F     91          96

In [45]:
cse_avg = cse['Marks'].mean()
cse[cse['Marks'] > cse_avg]

  Student Department Gender  Marks  Attendance
0       A        CSE      F     85          92
6       G        CSE      F     95          98

In [46]:
ece_avg = ece['Marks'].mean()
ece[ece['Marks'] > ece_avg]

  Student Department Gender  Marks  Attendance
2       C        ECE      F     91          96
5       F        ECE      F     88          90

In [47]:
cse_att = cse['Attendance'].mean()
ece_att = ece['Attendance'].mean()

if cse_att > ece_att:
    print("CSE")
else:
    print("ECE")

CSE

df = pd.DataFrame({ 'ID': [101,102,103,101,104,102,105],  
'Name': ['A','B','C','A','D','B','E'],
'Age': [20,21,22,20,23,21,24],  
'Score': [80,75,90,85,88,75,92] })  
Perform:
1. Identify duplicated IDs.
2. For each ID, determine whether its records are identical.
3. If multiple records exist for an ID, retain the record having the highest
Score.
4. Produce a clean DataFrame containing exactly one record per ID.
5. Report how many records were removed.

In [48]:
import pandas as pd

df = pd.DataFrame({
    'ID': [101,102,103,101,104,102,105],
    'Name': ['A','B','C','A','D','B','E'],
    'Age': [20,21,22,20,23,21,24],
    'Score': [80,75,90,85,88,75,92]
})

In [49]:
df[df['ID'].duplicated(keep=False)]

    ID Name  Age  Score
0  101    A   20     80
1  102    B   21     75
3  101    A   20     85
5  102    B   21     75

In [50]:
for id in df['ID'].unique():
    records = df[df['ID'] == id]

    if len(records) > 1:
        if len(records.drop_duplicates()) == 1:
            print(id, "Identical")
        else:
            print(id, "Not identical")

101 Not identical
102 Identical

In [51]:
clean_df = df.sort_values('Score', ascending=False).drop_duplicates(
    'ID', keep='first'
)
print(clean_df)

    ID Name  Age  Score
6  105    E   24     92
2  103    C   22     90
4  104    D   23     88
3  101    A   20     85
1  102    B   21     75

In [52]:
clean_df = clean_df.sort_values('ID').reset_index(drop=True)
print(clean_df)

    ID Name  Age  Score
0  101    A   20     85
1  102    B   21     75
2  103    C   22     90
3  104    D   23     88
4  105    E   24     92

In [53]:
len(df) - len(clean_df)

2

df = pd.DataFrame({ 'Date': [ '2026-01-01',
'2026-01-02',
'2026-01-04',
'2026-01-05',
'2026-01-08',
'2026-01-09' ],  
'Sales': [100,120,150,130,180,200] })  
Perform:
1. Convert Date into a proper datetime column.
2. Detect the missing dates.
3. Reindex the DataFrame to contain every date between the minimum and
maximum date.
4. Keep missing sales as NaN.
5. Calculate a 3-day rolling average of sales.
6. Identify the date on which the rolling average is maximum.

In [54]:
import pandas as pd

df = pd.DataFrame({
    'Date': [
        '2026-01-01',
        '2026-01-02',
        '2026-01-04',
        '2026-01-05',
        '2026-01-08',
        '2026-01-09'
    ],
    'Sales': [100, 120, 150, 130, 180, 200]
})

In [55]:
df['Date'] = pd.to_datetime(df['Date'])
print(df.dtypes)

Date     datetime64[ns]
Sales             int64
dtype: object

In [56]:
min_d = df['Date'].min()
max_d = df['Date'].max()

all_d = pd.date_range(start=min_d, end=max_d)

missing_d= all_d.difference(df['Date'])

print("Missing dates:")
print(missing_d)

Missing dates:
DatetimeIndex(['2026-01-03', '2026-01-06', '2026-01-07'], dtype='datetime64[ns]', freq=None)

In [57]:
df = df.set_index('Date')
df = df.reindex(all_d)
print(df)

            Sales
2026-01-01  100.0
2026-01-02  120.0
2026-01-03    NaN
2026-01-04  150.0
2026-01-05  130.0
2026-01-06    NaN
2026-01-07    NaN
2026-01-08  180.0
2026-01-09  200.0

In [59]:
df['Rolling_Avg'] = df['Sales'].rolling(window=3).mean()
print(df)

            Sales  Rolling_Avg
2026-01-01  100.0          NaN
2026-01-02  120.0          NaN
2026-01-03    NaN          NaN
2026-01-04  150.0          NaN
2026-01-05  130.0          NaN
2026-01-06    NaN          NaN
2026-01-07    NaN          NaN
2026-01-08  180.0          NaN
2026-01-09  200.0          NaN

In [61]:
max_d = df['Rolling_Avg'].idxmax()

print(max_d)

NaT

/tmp/ipykernel_1344/742693077.py:1: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_d = df['Rolling_Avg'].idxmax()